# Question Answering Leaderboard Example

In [1]:
import pandas as pd
import requests

In [2]:
TEAM_NAME = "Matterhorn"

In [3]:
BASE_URL = "http://durham-leaderboard-runai-innovation-klemen.inference.compute.datascience.ch"
leaderboard_endpoint = f"{BASE_URL}/api/v1/leaderboard"
submit_endpoint = f"{BASE_URL}/api/v1/submit"


def get_leaderboard() -> pd.DataFrame:
    leaderboard = requests.get(leaderboard_endpoint).json()
    return pd.DataFrame(leaderboard["entries"])


def submit(df: pd.DataFrame, user: str, token: str) -> pd.Series:
    if user == "your_team_name" or user == "":
        raise ValueError("Please set your team name in the 'TEAM_NAME' variable.")
    predictions = df[["question", "answer"]].to_dict(orient="records")
    submission = {"predictions": predictions}
    print(predictions)
    response = requests.post(submit_endpoint, json=submission, auth=(user, token))
    if (response.status_code // 100) != 2:
        response.raise_for_status()
    print(response.json())
    return pd.Series(response.json())

In [4]:
get_leaderboard()

,user_name,rank,attempt,timestamp,metrics
0,ALPHUBEL,1,3,2026-06-03T09:42:19.973459,"{'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,..."
1,Matterhorn,1,55,2026-06-03T10:46:38.284943,"{'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0,..."
2,Zinalrothorn,3,22,2026-06-02T14:52:30.048258,"{'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.0,..."

In [6]:
df = pd.read_csv("//Users//lalitaneeharikavajjhala//Desktop//Final Submission File.csv", encoding="utf-8", sep=",", dtype = {"question" : str}).fillna("")
df.head(10)

,question,answer
0,What year where there most casualties from man...,"2002. In that year, more than 10,000 casualtie..."
1,In what year did the quantity of man-made disa...,Man-made disasters peaked in 2005.
2,Between 1970 and 2023 what year in the data sh...,2023. There were 218 natural catastrophes.
3,What year between 1994 and 2023 had the most h...,"2011, with 6 high-severity natural catastrophes."
4,How much higher are the 2023 insured losses th...,The 2023 insured losses were 21% higher than t...
5,Which figure shows the trend in insured losses...,Figure 4. The highest insured-loss year on rec...
6,"Before 2023, what was the highest year on reco...",2021
7,What regions does the Swiss Re report on natur...,The Swiss Re report splits the US into the mid...
8,What is the highest Benefit to Cost ratio buil...,Earthquake-resistant building codes have the h...
9,According to the Swiss Re Institute report on ...,"Hurricanes Harvey, Irma and Maria contributed ..."

In [7]:
submit(df, user=TEAM_NAME, token="cant_be_empty")

[{'question': 'What year where there most casualties from man-made disasters in the recorded data?', 'answer': '2002. In that year, more than 10,000 casualties were attributed to man-made catastrophes.'}, {'question': 'In what year did the quantity of man-made disasters peak in the recorded data between 1970 and 2023?', 'answer': 'Man-made disasters peaked in 2005.'}, {'question': 'Between 1970 and 2023 what year in the data shows the largest number of natural catastrophes?', 'answer': '2023. There were 218 natural catastrophes.'}, {'question': 'What year between 1994 and 2023 had the most high severity ($5 billion in damages or more) natural catastrophes?', 'answer': '2011, with 6 high-severity natural catastrophes.'}, {'question': 'How much higher are the 2023 insured losses than the previous 10 year average?', 'answer': 'The 2023 insured losses were 21% higher than the previous 10-year average, representing an increase from USD 89 billion to USD 108 billion.'}, {'question': 'Which figure shows the trend in insured losses over data from 1994 to 2023? In this figure, what is the highest insured loss year on record?', 'answer': 'Figure 4. The highest insured-loss year on record was 2017.'}, {'question': 'Before 2023, what was the highest year on record for European Severe Convective Storm losses?', 'answer': '2021'}, {'question': 'What regions does the Swiss Re report on natural catastrophes split the US into for severe convective storm risk?', 'answer': 'The Swiss Re report splits the US into the midwest, central US, southeast, northeast, Rockies, and West for severe convective storm risk.'}, {'question': 'What is the highest Benefit to Cost ratio building code element described in the Swiss Re report on natural catastrophes?', 'answer': 'Earthquake-resistant building codes have the highest benefit-to-cost ratio, at 12:1.'}, {'question': 'According to the Swiss Re Institute report on natural catastrophes, 2017 was a standout year in terms of insured loss damages. What were the names of the weather events which contributed most to this figure?', 'answer': 'Hurricanes Harvey, Irma and Maria contributed most to the 2017 insured-loss figure.'}, {'question': 'Given how the Swiss Re Institute classifies primary and secondary perils, to which category can we attribute more losses in 2023? How is insurance claim tracking characterized in this category?', 'answer': 'In 2023, secondary perils accounted for the majority of losses with USD 87 billion (81%), a category characterized by "weaker exposure data capture and claims tracking."'}, {'question': 'In historical data from the Swiss Re Institute, which geographical grouping of countries has the smallest proportion of insured losses to uninsured losses between 2014 and 2023?', 'answer': 'Africa has the smallest proportion of insured losses relative to uninsured losses between 2014 and 2023.'}, {'question': 'What is the lower bound of dead or missing which have to be reported in connection to a natural catastrophe in order for the Swiss Re data to report it in their statistics?', 'answer': 'According to the Swiss Re sigma thresholds for 2023, the lower bound for dead or missing casualties that must be reported for a natural catastrophe to be included in their statistics is 20.'}, {'question': 'Excluding the overall UN average, which group of nations have more than 100 mobile broadband subscriptions per 100 residents in 2024?', 'answer': 'Europe, with 105.2 active mobile-broadband subscriptions per 100 inhabitants in 2024.'}, {'question': 'According to survey data, which feature of government web-portals experienced the largest between 2022 and 2024?', 'answer': 'The feature was the ability for individuals to modify their own data online, which increased from 50% in 2022 to 56% in 2024, a rise of 6 percentage points.'}, {'question': 'When were the simplified four stages of E-government adoption published? Which revision of the EGDI is this related to?', 'answer': 'The simplified four stages were used from 2010 to 2014 under EGDI rev2.0.'}, {'question': 'Between what years was the EGDI revision 3.0 acive?', 'answer': 'According to Figure 1.1 in the report, the EGDI revision 3.0 was active between 2014 and 2020.'}, {'question': 'Given when academic articles using the term started being published, when were the terms E-government development index and Online services index introduced?', 'answer': '2003'}, {'question': 'Of the questions highlighted from the Member States Questionnaire in a chart, is there a discontinuity in the numbering of the questions featured? If so, which numbers are missing?', 'answer': 'Yes. Questions #21 and #22 are missing from the displayed sequence.'}, {'question': 'What was the percentage increase over all the 193 UN member states in EGDI scores between 2022 and 2024?', 'answer': 'The average EGDI value for all 193 UN Member States increased by 4.59% between 2022 and 2024.'}, {'question': 'Of the countries with very high OSI levels and high EGDI divergence what is the one with the lowest Telecommunications Infrasructure Index?', 'answer': 'Rwanda has the lowest Telecommunications Infrastructure Index level among the listed countries with very high OSI levels and divergent EGDI components.'}, {'question': 'What grouping of nations has the closest OSI subindex average to the overall UN 193 average?', 'answer': 'The Americas have the OSI subindex average closest to the overall UN 193 average: 0.5797, compared with the global average of 0.5754.'}, {'question': 'Why did the average number of provided online services increase while the percentage stayed the same between 2022 and 2024? How many services were assessed in each of the 2 years?', 'answer': 'The average number of online services increased from 16 to 18 while the percentage remained roughly the same (72-73 per cent) because the total number of services assessed increased from 22 in 2022 to 25 in 2024.'}, {'question': 'What percentage of european countries support filing income tax online?', 'answer': '98% of European countries support filing income tax online.'}, {'question': 'In what percentage of countries in Oceania is one able to apply for a death certificate through a fully digitized process?', 'answer': '14% of countries in Oceania allow users to apply for a death certificate through a fully digitized process.'}, {'question': 'What region of the world contains the countries that enable fully digitized vehicle regitration? What is the percentage of countries in this region that support this?', 'answer': 'Asia is the region containing countries that enable fully digitized motor-vehicle registration. The proportion is 2%.'}, {'question': 'In what percentage of countries in the Americas is one able to apply for disability compensation in at least a partially online manner?', 'answer': '63% of countries in the Americas provide at least a partially online way to apply for disability-compensation benefits. A further 20% provide a fully digitalized process.'}, {'question': 'What number of countries in Africa support digital invoicing? What is the percentage increase in that figure since 2022?', 'answer': '14 countries in Africa support digital invoicing, representing a 7.4% increase since 2022.'}, {'question': 'What number of countries in Europe offer an E-procurement platform? Not percentage, number of countries.', 'answer': 'In Europe, 40 countries offer an e-procurement platform in 2024'}, {'question': 'What fully digital service for individuals in vulnerable situations experienced the largest percentge decline between 2022 and 2024?', 'answer': 'The fully digital service for individuals in vulnerable situations that experienced the largest percentage decline between 2022 and 2024 was services for immigrants, which saw a 13.5 per cent decline.'}, {'question': 'What service for individuals in vulnerable situations has no fully digitized component in Oceania?', 'answer': 'Services for women.'}, {'question': 'What proportion of countries offer judiciary services in a way that is accessible on mobile or through an app?', 'answer': '65% of countries offer justice services that are accessible through a mobile device browser or app.'}, {'question': 'What landlocked countries have moved from high to very high E-government development index in the survey period?', 'answer': 'The landlocked countries that moved from the high to the very high E-government development index group are Armenia, Azerbaijan, Mongolia, the Republic of Moldova, and Uzbekistan.'}, {'question': 'What small island nation moved from the middle to the high EGDI group in the last survey period?', 'answer': 'Vanuatu is the small island nation that moved from the middle to the high EGDI group in the last survey period.'}, {'question': "How has Japan named their initiative for removing bureaucratic inefficiencies and improving their digital government tools? What is the project's initial budget?", 'answer': 'Japan named the project the Digital Garden City Nation Initiative. Its initial budget was USD 42 billion.'}, {'question': 'What two departments of the UK govenrment have been merged in the effort to enhance their digital transformation?', 'answer': "The Government Digital Service (GDS) and the Department for Science, Innovation, and Technology (DSIT) have been merged to enhance the UK's digital transformation."}, {'question': "What country grouping appears to have the most drastic difference between EGDI levels of it's constituents?", 'answer': 'Oceania appears to have the most drastic variation in EGDI levels among its constituent countries. EGDI values range from 0.3076 to 0.9577.'}, {'question': 'What is the change in percentage of cities providing information on procurement between 2022 and 2024?', 'answer': 'The change in percentage of cities providing information on procurement between 2022 and 2024 is 6 percentage points for procurement announcements (from 53% to 59%) and 2 percentage points for procurement results (from 40% to 42%) and for the adoption of e-procurement platforms (from 36% to 42% and then rounded, but the original value is 36% to 42% or 6 percentage points).'}, {'question': 'In the year before the two investment segments equalized, what was the amount invested in energy transition power generation vs fossil fuel power generation?', 'answer': 'In 2021, energy-transition power-generation investment was USD 849 billion, compared with USD 896 billion for fossil-fuel power generation.'}, {'question': 'How many of the top 10 costliest environmental disasters of 2023 occurred in Latin America? Which country faced the msot expensive one?', 'answer': 'Three of the top 10 costliest economic-loss events of 2023 occurred in Latin America. Mexico faced the most expensive one: Hurricane Otis.'}]

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [8]:
res = get_leaderboard()

In [9]:
import pandas as pd

# Show all rows
pd.set_option('display.max_rows', None)

# Show all columns
pd.set_option('display.max_columns', None)

# Don't truncate column width
pd.set_option('display.max_colwidth', None)

# Make display wider
pd.set_option('display.width', None)

# Show full content of wide dataframes
pd.set_option('display.expand_frame_repr', False)

In [10]:
res

      user_name  rank  attempt                   timestamp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           metrics
0      ALPHUBEL     1        3  2026-06-03T09:42:19.973459  {'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0], 'difficulty': [2.0, 2.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 2.0, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 1.5, 1.0], 'total_score': 0.6513761467889908, 'questions_answered': 37, 'total_questions': 40}
1    Matterhorn     1       55  2026-06-03T10:46:38.284943  {'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'difficulty': [2.0, 2.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 2.0, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 1.5, 1.0], 'total_score': 0.6513761467889908, 'questions_answered': 37, 'total_questions': 40}
2  Zinalrothorn     3       22  2026-06-02T14:52:30.048258  {'scores': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.0, 0.5, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.5], 'difficulty': [2.0, 2.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.5, 1.5, 2.0, 1.5, 1.5, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 1.5, 1.0], 'total_score': 0.3302752293577982, 'questions_answered': 20, 'total_questions': 40}